# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-19 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_auto_20190919_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
