# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-19 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0007_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
