# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-19 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0009_remove_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1950-01-01'),
            preserve_default=False,
        ),
    ]
